task: detection
dataset:
  name: deepfashion2
  cfg:
    split: train
    transforms:
      name: DeepFashionObjectDetectionDefaultTransform
      cfg:
        train: true
model:
  name: fasterrcnn_resnet50_fpn_v2
  cfg:
    num_classes: 14
    weights:
      name: FasterRCNN_ResNet50_FPN_V2_Weights
      checkpoint: COCO_V1
    weights_backbone:
      name: ResNet50_Weights
      checkpoint: IMAGENET1K_V2
    debug: true